### ISSUE TITLE
Create use-cases for client usage of MMS 

### ISSUE THREAD

**Issue by johtoblan** [metno/py-mms#10]
- Questions to be answered: Do we need an iterable queue? (If more than one message is to be sent per client call?)
- More questions should be defned.

**Comment by mpejcoch** [comment]
Should be in sync with https://github.com/metno/MMS/wiki/Client-commands

**Comment by johtoblan** [comment]
Not so much client commands as to simplify usage of the client command

**Comment by mpejcoch** [comment]
Might need some help from @lcoram
