### ISSUE TITLE
How would you install this on a production system? Is setup.py missing?

### ISSUE THREAD

**Issue by TAlonglong** [metno/py-mms#19]
How would you install this on a production system?

Normally I would expect a setup.py to handle this.

https://packaging.python.org/tutorials/packaging-projects/#configuring-metadata

**Comment by TAlonglong** [comment]
Something like this:

```
#!/usr/bin/python
"""
"""

from setuptools import setup

setup(name="py-mms",
      version="0.0.1",
      description='python mms client',
      author='Met norway',
      author_email='post@met.no',
      classifiers=["Development Status :: 4 - Beta",
                   "Intended Audience :: Science/Research",
                   "License :: OSI Approved :: GNU General Public License v3 " +
                   "or later (GPLv3+)",
                   "Operating System :: OS Independent",
                   "Programming Language :: Python",
                   "Topic :: Scientific/Engineering"],
      url="https://github.com/metno/py-mms.git",
      packages=['pymms'],
      zip_safe=False,
      )
```

**Comment by vkbo** [comment]
I can add the necessary files, sure.

Just a note to add: `pyproject.toml`, `setup.cfg` and `setup.py`.

**Comment by vkbo** [comment]
I think @mpejcoch wanted to install it in a different way, but it doesn't hurt to support standard site-package install too.

**Comment by mpejcoch** [comment]
> I think @mpejcoch wanted to install it in a different way, but it doesn't hurt to support standard site-package install too.

What we need is to have it available as an environment module, though we can provide other installation options too, so feel free to add those.
