### ISSUE TITLE
What timestamp if any should be used?

### ISSUE THREAD

**Issue by johtoblan** [metno/py-mms#2]
Maybe a difference in Windows and Linux timestamps. Decide on how to handle this.

**Comment by vkbo** [comment]
Seems that the python time module returnes a float of seconds since the epoch, but the epoch itself is platform dependant.
https://docs.python.org/3/library/time.html#epoch

If we allow for a float representation of a timestamp, it should be converted on the fly from a string or a datetime object.

**Comment by mpejcoch** [comment]
In which context is this meant? For the event field I think we should go for ISO 8601 with the necessary precision.  YYYY-MM-DDThh:mm:ss.sssZ ?

**Comment by vkbo** [comment]
We were talking about having an option to convert the timestamps to a more pythonic format. Either time.time() like or a datetime.datetime object.

**Comment by mpejcoch** [comment]
ISO8601 with milliseconds.
